name: Deploy Next.js SSR App to Firebase on dev push

on:
  push:
    branches:
      - dev

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # Install project dependencies
      - run: pnpm install

      # Inject .env from secrets
      - name: Inject .env from secrets
        run: |
          echo "WONDER_RPC_URL=${{ secrets.WONDER_RPC_URL }}" >> .env
          echo "NODE_ENV=production" >> .env
          echo "NEXT_PUBLIC_FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}" >> .env
          echo "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }}" >> .env
          echo "NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}" >> .env
          echo "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }}" >> .env
          echo "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}" >> .env
          echo "NEXT_PUBLIC_FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}" >> .env
          echo "NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID }}" >> .env
          echo "NEXT_PUBLIC_ALCHEMY_API_KEY=${{ secrets.ALCHEMY_API_KEY }}" >> .env

      # Build Next.js app
      - run: pnpm build

      # Install Firebase CLI
      - run: npm install -g firebase-tools

      # Deploy Hosting + Functions
      - name: Deploy to Firebase
        run: firebase deploy --project daxfi-7db30 --only hosting,functions --token "${{ secrets.FIREBASE_TOKEN }}"
